export const ALL_TAGS = [
  'cake',
  'cookies',
  'bread',
  'pastry',
  'chocolate',
  'lemon',
  'chicken',
  'beef',
  'seafood',
  'pasta',
  'soup',
  'salad',
  'dessert',
  'breakfast',
  'indian',
  'italian',
  'french',
  'vegetarian',
  'mexican',
  'asian',
  'mediterranean',
  'vegan',
  'gluten-free',
  'quick',
  'slow-cooker',
  'pork',
]

export const TAG_ICONS: Record<string, string> = {
  cake: '🎂',
  cookies: '🍪',
  bread: '🍞',
  pastry: '🥐',
  chocolate: '🍫',
  lemon: '🍋',
  chicken: '🍗',
  beef: '🥩',
  seafood: '🐟',
  pasta: '🍝',
  soup: '🍲',
  salad: '🥗',
  dessert: '🍮',
  breakfast: '🍳',
  indian: '🍛',
  italian: '🇮🇹',
  french: '🥖',
  vegetarian: '🥦',
  mexican: '🌮',
  asian: '🥢',
  mediterranean: '🫒',
  vegan: '🌱',
  'gluten-free': '🌾',
  quick: '⚡',
  'slow-cooker': '🍲',
  pork: '🐖'
}
