export const ALL_TAGS = [
  "asian",
  "beef",
  "beverage",
  "bread",
  "breakfast",
  "cake",
  "chicken",
  "chocolate",
  "cookies",
  "dessert",
  "french",
  "gluten-free",
  "indian",
  "italian",
  "lemon",
  "mediterranean",
  "mexican",
  "pasta",
  "pastry",
  "pork",
  "quick",
  "salad",
  "seafood",
  "slow-cooker",
  "soup",
  "vegan",
  "vegetarian",
];

export const TAG_ICONS: Record<string, string> = {
  asian: "🥢",
  beef: "🥩",
  beverage: "🧋",
  bread: "🍞",
  breakfast: "🍳",
  cake: "🎂",
  chicken: "🍗",
  chocolate: "🍫",
  cookies: "🍪",
  dessert: "🍮",
  french: "🥖",
  "gluten-free": "🌾",
  indian: "🍛",
  italian: "🇮🇹",
  lemon: "🍋",
  mediterranean: "🫒",
  mexican: "🌮",
  pasta: "🍝",
  pastry: "🥐",
  pork: "🐖",
  quick: "⚡",
  salad: "🥗",
  seafood: "🐟",
  "slow-cooker": "🍲",
  soup: "🍲",
  vegan: "🌱",
  vegetarian: "🥦",
};
